// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dummyuser

import (
	"database/sql"
)

type User struct {
	ID           int64
	Name         string
	Email        string
	Bio          sql.NullString
	Roles        sql.NullString
	PasswordHash string
}
